
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: your_username
      RABBITMQ_DEFAULT_PASS: your_password
    ports:
      - "15672:15672"  
      - "5672:5672"   
    networks:
    - microservices_network

  messaging-service:
    build:
      context: ./messaging-service
      dockerfile: Dockerfile
    environment:
      RABBITMQ_USER: your_username
      RABBITMQ_PASSWORD: your_password
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8001:8000"  
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - microservices_network

  auth-service:
    build: ./auth-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/auth_db?sslmode=disable
      - SECRET_KEY=your_secret_key
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - microservices_network

  products-service:
    build: ./products-service
    ports:
      - "8003:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/costmeticos
    networks:
      - microservices_network
      
networks:
  microservices_network:
    driver: bridge

volumes:
  postgres_data: