version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/authdb
    depends_on:
      - db
