version: '1'

services:
  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/auth_db
    depends_on:
      - postgres
    networks:
      - microservices_network

  # product-service:
  #   build: ./product-service
  #   container_name: product_service
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@postgres:5432/products_db
  #   depends_on:
  #     - postgres
  #   networks:
  #     - microservices_network

  # cart-service:
  #   build: ./cart-service
  #   container_name: cart_service
  #   ports:
  #     - "8003:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@postgres:5432/cart_db
  #   depends_on:
  #     - postgres
  #   networks:
  #     - microservices_network

  # celery-worker:
  #   build: ./celery-worker
  #   container_name: celery_worker
  #   depends_on:
  #     - redis
  #   networks:
  #     - microservices_network

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - microservices_network

  # redis:
  #   image: redis:6.0-alpine
  #   container_name: redis
  #   networks:
  #     - microservices_network

  # rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  postgres_data:
